baseURL = "https://pbrisbin.com/"
googleAnalytics = "UA-22304237-1"
languageCode = "en-us"
title = "pbrisbin dot com"
theme = "mini-mod"


[markup]
  [markup.highlight]
    style = "lovelace"

[social]
  github = "https://github.com/pbrisbin"
  twitter = "https://twitter.com/patbrisbin"

[params]
  copyright = "© pbrisbin dot com 2008 - forever"
  enableGoogleAnalytics = true
